// KSLSA silvi-zone species statement, as issued by IAFT.
//
// This is reference data, not logic. The platform reads it; it does not form
// opinions about species. Ten agro-climatic zones regrouped into four silvi
// zones, five agroforestry models, species eligible per zone × model.
//
// Source: "Statement showing the list of Forest Species suitable for different
// Silvi Zones (Model wise) in Karnataka", IAFT, for the KSLSA project.

export type Model = {
  key: string;
  en: string;
  kn: string;
  category: string;      // what kind of species the model draws on
  bag: string;           // polybag size
  spacingEn: string;
  density: number;       // plants per hectare, or per km for linear models
  densityUnit: "ha" | "km";
  note?: string;
};

export const MODELS: Model[] = [
  {
    key: "bund",
    en: "Bund / Strip / Shelter belt / Hedge / Alley planting",
    kn: "ಬದು / ಪಟ್ಟಿ / ತಡೆಪಟ್ಟಿ / ಬೇಲಿ ನೆಡುವಿಕೆ",
    category: "NTFP",
    bag: '14" × 20"',
    spacingEn: "10 m × 10 m",
    density: 100,
    densityUnit: "ha",
  },
  {
    key: "block",
    en: "Block / Cluster plantation",
    kn: "ಬ್ಲಾಕ್ / ಸಮೂಹ ನೆಡುತೋಪು",
    category: "Timber",
    bag: '8" × 12"',
    spacingEn: "10 m × 5 m, or 5 m × 5 m",
    density: 200,
    densityUnit: "ha",
    note: "5 m × 5 m gives 400 per ha. Teak at 3 m × 3 m or 2 m × 2 m.",
  },
  {
    key: "linear",
    en: "Linear / Roadside / Canal bank plantation",
    kn: "ರೇಖೀಯ / ರಸ್ತೆ ಬದಿ / ಕಾಲುವೆ ದಂಡೆ",
    category: "NTFP / Timber",
    bag: '14" × 20"',
    spacingEn: "7 m × 7 m",
    density: 300,
    densityUnit: "km",
  },
  {
    key: "gua",
    en: "Greening of Urban Area",
    kn: "ನಗರ ಹಸಿರೀಕರಣ",
    category: "Flowering",
    bag: '14" × 20"',
    spacingEn: "7 m × 7 m",
    density: 300,
    densityUnit: "km",
  },
  {
    key: "institution",
    en: "School / Institute / Temple premises / Grave yard planting",
    kn: "ಶಾಲೆ / ಸಂಸ್ಥೆ / ದೇವಸ್ಥಾನ ಆವರಣ ನೆಡುವಿಕೆ",
    category: "Flowering / Shade / Fruit",
    bag: '14" × 20"',
    spacingEn: "10 m × 10 m",
    density: 100,
    densityUnit: "km",
  },
];

export type SilviZone = {
  key: string;
  en: string;
  kn: string;
  agroZones: { en: string; districts: string }[];
};

export const SILVI_ZONES: SilviZone[] = [
  {
    key: "dry",
    en: "Dry Zone",
    kn: "ಒಣ ವಲಯ",
    agroZones: [
      { en: "North Eastern Transition Zone", districts: "Bidar · Kalaburagi (Chincholi, Aland)" },
      { en: "North Eastern Dry Zone", districts: "Kalaburagi · Raichur (Devadurga, Manvi, Raichur)" },
      { en: "North Dry Zone", districts: "Vijayapura · Bagalkote · Koppal · Raichur (Lingsugur, Sindhanur) · Ballari · Davanagere (Harapanahalli) · Gadag (Navalgund) · Belagavi (Gokak Forest Division)" },
      { en: "Central Dry Zone", districts: "Chitradurga · Davanagere · Tumakuru · Hassan (Arasikere) · Chikkamagaluru (Kadur)" },
      { en: "Eastern Dry Zone", districts: "Tumakuru (Gubbi, Tumkur) · Bengaluru Rural · Bengaluru Urban (Bangalore North, Bangalore South, Anekal) · Kolar · Chikkaballapura" },
      { en: "Southern Dry Zone", districts: "Mysuru · Chamarajanagara · Tumakuru (Turuvekere, Kunigal) · Mandya · Hassan (Channarayapatna)" },
    ],
  },
  {
    key: "transitional",
    en: "Transitional Zone",
    kn: "ಪರಿವರ್ತನ ವಲಯ",
    agroZones: [
      { en: "Southern Transition Zone", districts: "Hassan · Chikkamagaluru (Tarikere) · Shivamogga (Bhadravati, Shivamogga, Shikaripura) · Davanagere (Honnali, Channagiri) · Mysuru (H.D. Kote, Hunsur, Periyapatna)" },
      { en: "Northern Transition Zone & North Eastern", districts: "Belagavi (Hukkeri, Chikkodi, Bailhongal, Belagavi) · Dharwad (Dharwad, Hubli, Kundgol)" },
      { en: "Northern Eastern Transition Zone", districts: "Haveri · Gadag (Shirahatti)" },
    ],
  },
  {
    key: "hilly",
    en: "Hilly Zone",
    kn: "ಗುಡ್ಡಗಾಡು ವಲಯ",
    agroZones: [
      { en: "Hilly Zone", districts: "Uttara Kannada (Sirsi, Siddapur, Yellapur, Supa, Haliyal, Mundagod) · Belagavi (Khanapur) · Shivamogga (Sorab, Hosanagara, Sagar, Tirthahalli) · Chikkamagaluru · Dharwad (Kalaghatagi) · Haveri (Hanagal) · Kodagu · Hassan (Sakaleshapura)" },
    ],
  },
  {
    key: "coastal",
    en: "Coastal Zone",
    kn: "ಕರಾವಳಿ ವಲಯ",
    agroZones: [
      { en: "Coastal Zone", districts: "Uttara Kannada (Karwar, Kumta, Honnavar, Bhatkal, Ankola) · Udupi (Kundapura, Karkala, Udupi) · Dakshina Kannada (Mangaluru, Bantwala, Belthangady, Puttur, Sullia)" },
    ],
  },
];

export type Species = { sci: string; local: string };

/** Eligible species by silvi zone and model, exactly as the statement lists them. */
export const SPECIES_MATRIX: Record<string, Record<string, Species[]>> = {
  dry: {
    bund: [
      { sci: "Aegle marmelos", local: "Bilva" },
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Buchanania lanzan", local: "Murki" },
      { sci: "Cordia dicotoma", local: "Challe" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Feronia elephantum", local: "Bela" },
      { sci: "Ficus benghalensis", local: "Aale" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Sapindus trifoliatus", local: "Antuwaal" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
    ],
    block: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Annona squamosa", local: "Seetaphal" },
      { sci: "Dendrocalamus stocksii", local: "Maarihal Bamboo" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Melia dubia", local: "Hebbevu" },
      { sci: "Moringa oleifera", local: "Nugge" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Pterocarpus santalinus", local: "Red Sander" },
      { sci: "Santalum album", local: "Sandal" },
      { sci: "Swietenia mahogany", local: "Mahagani" },
      { sci: "Tectona grandis", local: "Teak" },
    ],
    linear: [
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Bombax ceiba", local: "Buraga" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Ficus benghalensis", local: "Aale" },
      { sci: "Holoptelea integrifolia", local: "Tapasi" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pithecellobium dulce", local: "Sihihunshe" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
      { sci: "Terminalia arjuna", local: "Hole matti" },
      { sci: "Terminalia bellirica", local: "Taare" },
    ],
    gua: [
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Jacaranda mimosifolia", local: "Jakaranda" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Magnolia champaca", local: "Sampige" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Peltophorum pterocarpum", local: "Peltophorum" },
      { sci: "Spathodea campanulata", local: "Spethodia" },
      { sci: "Tecoma argentea", local: "Techoma" },
      { sci: "Terminalia catappa", local: "Kaadu badami" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
    institution: [
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Phyllanthus acidus", local: "Kadagol Nelli" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
  },

  transitional: {
    bund: [
      { sci: "Aegle marmelos", local: "Bilva" },
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Buchanania lanzan", local: "Murki" },
      { sci: "Cordia dicotoma", local: "Challe" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Feronia elephantum", local: "Bela" },
      { sci: "Gmelina arborea", local: "Shivani" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Sapindus trifoliatus", local: "Antuwaal" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
    ],
    block: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Annona squamosa", local: "Seetaphal" },
      { sci: "Dendrocalamus stocksii", local: "Maarihal Bamboo" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Melia dubia", local: "Hebbevu" },
      { sci: "Moringa oleifera", local: "Nugge" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Pterocarpus santalinus", local: "Red Sander" },
      { sci: "Santalum album", local: "Sandal" },
      { sci: "Swietenia mahogany", local: "Mahagani" },
      { sci: "Tectona grandis", local: "Teak" },
      { sci: "Wrightia tinctoria", local: "Haale" },
    ],
    linear: [
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Bombax ceiba", local: "Buraga" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Ficus benghalensis", local: "Aale" },
      { sci: "Holoptelea integrifolia", local: "Tapasi" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pithecellobium dulce", local: "Sihihunshe" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
      { sci: "Terminalia arjuna", local: "Hole matti" },
      { sci: "Terminalia bellirica", local: "Taare" },
    ],
    gua: [
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Jacaranda mimosifolia", local: "Jakaranda" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Magnolia champaca", local: "Sampige" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Peltophorum pterocarpum", local: "Peltophorum" },
      { sci: "Spathodea campanulata", local: "Spethodia" },
      { sci: "Tecoma argentea", local: "Techoma" },
      { sci: "Terminalia catappa", local: "Kaadu badami" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
    institution: [
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Phyllanthus acidus", local: "Kadagol Nelli" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
  },

  hilly: {
    bund: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Gmelina arborea", local: "Shivani" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Sapindus trifoliatus", local: "Antuwaal" },
      { sci: "Syzygium cumini", local: "Nerale" },
    ],
    block: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Casuarina equisetifolia", local: "Casurina" },
      { sci: "Cinnamomum verum", local: "Dalchinni" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Dendrocalamus stocksii", local: "Maarihal Bamboo" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Garcinia cambogia", local: "Uppage" },
      { sci: "Garcinia indica", local: "Murgal" },
      { sci: "Melia dubia", local: "Hebbevu" },
      { sci: "Pterocarpus santalinus", local: "Red Sander" },
      { sci: "Santalum album", local: "Sandal" },
      { sci: "Swietenia mahogany", local: "Mahagani" },
      { sci: "Tectona grandis", local: "Teak" },
    ],
    linear: [
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Bombax ceiba", local: "Buraga" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Ficus benghalensis", local: "Aale" },
      { sci: "Holoptelea integrifolia", local: "Tapasi" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pithecellobium dulce", local: "Sihihunshe" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
      { sci: "Terminalia arjuna", local: "Hole matti" },
      { sci: "Terminalia bellirica", local: "Taare" },
    ],
    gua: [
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Jacaranda mimosifolia", local: "Jakaranda" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Magnolia champaca", local: "Sampige" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Peltophorum pterocarpum", local: "Peltophorum" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Spathodea campanulata", local: "Spethodia" },
      { sci: "Tecoma argentea", local: "Techoma" },
      { sci: "Terminalia catappa", local: "Kaadu badami" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
    institution: [
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Phyllanthus acidus", local: "Kadagol Nelli" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
  },

  coastal: {
    bund: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Gmelina arborea", local: "Shivani" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Sapindus trifoliatus", local: "Antuwaal" },
      { sci: "Syzygium cumini", local: "Nerale" },
    ],
    block: [
      { sci: "Anacardium occidentale", local: "Cashew" },
      { sci: "Casuarina equisetifolia", local: "Casurina" },
      { sci: "Cinnamomum verum", local: "Dalchinni" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Dendrocalamus stocksii", local: "Maarihal Bamboo" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Garcinia cambogia", local: "Uppage" },
      { sci: "Garcinia indica", local: "Murgal" },
      { sci: "Melia dubia", local: "Hebbevu" },
      { sci: "Pterocarpus santalinus", local: "Red Sander" },
      { sci: "Santalum album", local: "Sandal" },
      { sci: "Swietenia mahogany", local: "Mahagani" },
      { sci: "Tectona grandis", local: "Teak" },
    ],
    linear: [
      { sci: "Albizzia lebbeck", local: "Baage" },
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Bombax ceiba", local: "Buraga" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Dalbergia latifolia", local: "Beete" },
      { sci: "Ficus benghalensis", local: "Aale" },
      { sci: "Holoptelea integrifolia", local: "Tapasi" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Pithecellobium dulce", local: "Sihihunshe" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Pterocarpus marsupium", local: "Honne" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Tamarindus indica", local: "Hunse" },
      { sci: "Terminalia arjuna", local: "Hole matti" },
      { sci: "Terminalia bellirica", local: "Taare" },
    ],
    gua: [
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Jacaranda mimosifolia", local: "Jakaranda" },
      { sci: "Maduca indica", local: "Hippe" },
      { sci: "Magnolia champaca", local: "Sampige" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Peltophorum pterocarpum", local: "Peltophorum" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Spathodea campanulata", local: "Spethodia" },
      { sci: "Tecoma argentea", local: "Techoma" },
      { sci: "Terminalia catappa", local: "Kaadu badami" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
    institution: [
      { sci: "Artocarpus hirsutus", local: "Halasu" },
      { sci: "Azadirachta indica", local: "Bevu" },
      { sci: "Cassia fistula", local: "Kakke" },
      { sci: "Emblica officinalis", local: "Nelli" },
      { sci: "Mangifera indica", local: "Maavu" },
      { sci: "Millingtonia hortensis", local: "Aakash Mallige" },
      { sci: "Mimusops elengi", local: "Ranjal" },
      { sci: "Phyllanthus acidus", local: "Kadagol Nelli" },
      { sci: "Pongamia pinnata", local: "Honge" },
      { sci: "Syzygium cumini", local: "Nerale" },
      { sci: "Thespesia populnea", local: "Hoovarasi" },
    ],
  },
};

/** District → silvi zone, from the statement's district lists. */
export const DISTRICT_ZONE: Record<string, string> = {
  Bidar: "dry", Kalaburagi: "dry", Raichur: "dry", Vijayapura: "dry",
  Bagalkote: "dry", Koppal: "dry", Ballari: "dry", Vijayanagara: "dry",
  Chitradurga: "dry", Davanagere: "dry", Tumakuru: "dry", Kolar: "dry",
  Chikkaballapur: "dry", "Bengaluru Rural": "dry", "Bengaluru Urban": "dry",
  Ramanagara: "dry", Mysuru: "dry", Chamarajanagar: "dry", Mandya: "dry",
  Yadgir: "dry", Gadag: "dry",
  Hassan: "transitional", Shivamogga: "transitional", Dharwad: "transitional",
  Haveri: "transitional", Belagavi: "transitional",
  Chikkamagaluru: "hilly", Kodagu: "hilly", "Uttara Kannada": "hilly",
  Udupi: "coastal", "Dakshina Kannada": "coastal",
};

/** Land category → planting model. */
export const CATEGORY_MODEL: Record<string, string> = {
  "Revenue wasteland (Bane/Banjar)": "block",
  "Gomala / grazing land": "block",
  "Forest land - degraded": "block",
  "Forest land - blank area": "block",
  "Other government land": "block",
  "Panchayat land": "bund",
  "Tank foreshore / bund": "bund",
  "Canal bank": "linear",
  "Roadside / avenue strip": "linear",
  "Institutional campus (school, hospital, office)": "institution",
};

export const zoneFor = (district: string) => DISTRICT_ZONE[district] ?? "dry";
export const modelFor = (category: string) => CATEGORY_MODEL[category] ?? "block";
export const zone = (key: string) => SILVI_ZONES.find((z) => z.key === key);
export const model = (key: string) => MODELS.find((m) => m.key === key);
export const speciesFor = (zoneKey: string, modelKey: string): Species[] =>
  SPECIES_MATRIX[zoneKey]?.[modelKey] ?? [];
